data:
  name: mvseg_dataset
  finetune: true # if finetune is True, the dataset returns only items containing fine segmentations. Else, box segmentations.
  num_workers: 16
  seed: 1
  train_batch_size: 32
  val_batch_size: 1
  test_batch_size: 1
  batch_size: 1
model:
  name: deeplabv3
  encoder: resnet101
  finetune: true # if finetune is True, the target in the loss_fn will be the fine semantic segmentations, and not the boxes.
  normalize_features: true
  duplicate_optimizer_per_scale: true
  normalize_dt: false
  model: deeplabv3
train:
  seed: 0
  load_experiment: exp2_stage1_box
  epochs: 2000 #1500 for finetune
  log_every_iter: 20
  eval_every_iter: 100
  lr: 1.0e-04
  clip_grad: 1.0
  median_metrics:
  - loss/total # this loss is computed directly on the outputs of the networks
  q90_metrics:
  - loss/total
  
  
